version: "3"

services:
  interview_backend_coop_logistics:
    build: .
    container_name: interview_backend_coop_logistics
    environment:
      - APP_PORT=50051
    tty: true
    ports:
      - "50051:50051"
