version: "3.7"

services:
  interview_backend_coop_logistics:
    build: .
    container_name: interview_backend_coop_logistics
    environment:
      - APP_PORT=50051
    tty: true
    ports:
      - "50051:50051"
  techdocs:
    build:
      context: .
      dockerfile: docker-compose/Dockerfile
      target: techdocs
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
    ports:
      - "127.0.0.1:3000:3000/tcp"
      - "127.0.0.1:8000:8000/tcp"
    command: serve
volumes:
  xdg-cache-home: { }
  nothing: { }
